In [1]:
import numpy as np  # For numerical operations and generating random data
import pandas as pd  # For data manipulation and DataFrame operations
import sklearn
print("libraries loaded successfully!")

libraries loaded successfully!

In [2]:
# Set your file path to the csv file on your desktop
file_path = r"D:\Tushar\PD_LGD_EAD_Modeling_in-Python_-main\loan_data.csv"
try:
    # load data set from specified path
    df = pd.read_csv(file_path)
    # Create a new binary column'Default': 1 if risky status, else 0
    df['Default'] = df['loan_status'].apply(lambda x: 1 if x in ['Charged Off','Default','Late (31-120 days)'] else 0)
    # print the count of defaults(1) vs non-defaults(0)
    print("Default variable distribution:")
    print(df['Default'].value_counts())
    # Print how many loans fall into each original laon_status category
    print("\nLoan status distribution:")
    print(df['Loan_status'].value_counts())
except FileNotFoundError:
    # Print a helpful message if the file path is incorrect or file is missing
    print("File not found. Please check the file path.")
except Exception as e:
    # Catch and print any other unexpected errors
    print(f"An error occurred: {e}")

print(df['loan_status'].value_counts())

Default variable distribution:
Default
0    1190
1     810
Name: count, dtype: int64

Loan status distribution:
An error occurred: 'Loan_status'
loan_status
Current               418
In Grace Period       415
Late (31-120 days)    415
Charged Off           395
Fully Paid            357
Name: count, dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 75 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           2000 non-null   int64
 1   member_id                    2000 non-null   int64
 2   loan_amnt                    2000 non-null   int64
 3   funded_amnt                  2000 non-null   int64
 4   funded_amnt_inv              2000 non-null   int64
 5   term                         2000 non-null   object
 6   int_rate                     2000 non-null   float64
 7   installment                  2000 non-null   float64
 8   grade                        2000 non-null   object
 9   sub_grade                    2000 non-null   object
 10  emp_title                    1800 non-null   object
 11  emp_length                   2000 non-null   object
 12  home_ownership               2000 non-null   object
 13  annual_inc                   2000 non-null   int64
 14  verification_status          2000 non-null   object
 15  issue_d                      2000 non-null   object
 16  loan_status                  2000 non-null   object
 17  pymnt_plan                   2000 non-null   object
 18  url                          2000 non-null   object
 19  desc                         2000 non-null   object
 20  purpose                      2000 non-null   object
 21  title                        2000 non-null   object
 22  zip_code                     2000 non-null   object
 23  addr_state                   2000 non-null   object
 24  dti                          2000 non-null   float64
 25  delinq_2yrs                  2000 non-null   int64
 26  earliest_cr_line             2000 non-null   object
 27  inq_last_6mths               2000 non-null   int64
 28  mths_since_last_delinq       2000 non-null   int64
 29  mths_since_last_record       2000 non-null   int64
 30  open_acc                     2000 non-null   int64
 31  pub_rec                      2000 non-null   int64
 32  revol_bal                    2000 non-null   int64
 33  revol_util                   2000 non-null   float64
 34  total_acc                    2000 non-null   int64
 35  initial_list_status          2000 non-null   object
 36  out_prncp                    2000 non-null   float64
 37  out_prncp_inv                2000 non-null   float64
 38  total_pymnt                  2000 non-null   float64
 39  total_pymnt_inv              2000 non-null   float64
 40  total_rec_prncp              2000 non-null   float64
 41  total_rec_int                2000 non-null   float64
 42  total_rec_late_fee           2000 non-null   int64
 43  recoveries                   2000 non-null   float64
 44  collection_recovery_fee      2000 non-null   int64
 45  last_pymnt_d                 2000 non-null   object
 46  last_pymnt_amnt              2000 non-null   float64
 47  next_pymnt_d                 2000 non-null   object
 48  last_credit_pull_d           2000 non-null   object
 49  collections_12_mths_ex_med   2000 non-null   int64
 50  mths_since_last_major_derog  2000 non-null   int64
 51  policy_code                  2000 non-null   int64
 52  application_type             2000 non-null   object
 53  annual_inc_joint             0 non-null      float64
 54  dti_joint                    0 non-null      float64
 55  verification_status_joint    0 non-null      float64
 56  acc_now_delinq               2000 non-null   int64
 57  tot_coll_amt                 2000 non-null   int64
 58  tot_cur_bal                  2000 non-null   int64
 59  open_acc_6m                  2000 non-null   int64
 60  open_il_6m                   2000 non-null   int64
 61  open_il_12m                  2000 non-null   int64
 62  open_il_24m                  2000 non-null   int64
 63  mths_since_rcnt_il           2000 non-null   int64
 64  total_bal_il                 2000 non-null   int64
 65  il_util                      2000 non-null   float64
 66  open_rv_12m                  2000 non-null   int64
 67  open_rv_24m                  2000 non-null   int64
 68  max_bal_bc                   2000 non-null   int64
 69  all_util                     2000 non-null   float64
 70  total_rev_hi_lim             2000 non-null   int64
 71  inq_fi                       2000 non-null   int64
 72  total_cu_tl                  2000 non-null   int64
 73  inq_last_12m                 2000 non-null   int64
 74  Default                      2000 non-null   int64
dtypes: float64(17), int64(36), object(22)
memory usage: 1.1+ MB

In [4]:
df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,Default
count,2.000000e+03,2.000000e+03,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,...,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1.001000e+06,5.496737e+06,18109.070000,18109.070000,18059.193500,14.746390,627.211100,160366.295500,20.438990,2.06500,...,49.803150,4.441500,9.42900,9854.583500,50.315500,49718.322500,4.451500,9.595000,6.873000,0.405000
std,5.774946e+02,2.543201e+06,9727.868316,9727.868316,9726.600379,5.757953,341.409084,82274.114766,11.084245,1.40633,...,28.560396,2.833654,5.74016,5837.106738,28.876078,28435.514901,2.851265,5.719907,4.296056,0.491015
min,1.000000e+06,1.039353e+06,1082.000000,1082.000000,1012.000000,5.000000,35.330000,20093.000000,1.040000,0.00000,...,0.100000,0.000000,0.00000,2.000000,0.100000,55.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000500e+06,3.353874e+06,10027.750000,10027.750000,9961.500000,9.780000,339.427500,87956.500000,11.010000,1.00000,...,25.300000,2.000000,5.00000,4696.250000,25.300000,24410.500000,2.000000,5.000000,3.000000,0.000000
50%,1.001000e+06,5.421896e+06,18268.000000,18268.000000,18210.500000,14.705000,628.945000,161685.000000,20.485000,2.00000,...,50.500000,5.000000,9.00000,9716.500000,50.200000,51584.500000,4.000000,10.000000,7.000000,0.000000
75%,1.001499e+06,7.647814e+06,26503.750000,26503.750000,26454.250000,19.725000,913.455000,233910.250000,29.572500,3.00000,...,75.100000,7.000000,14.00000,14904.500000,75.325000,73225.250000,7.000000,14.000000,11.000000,1.000000
max,1.001999e+06,9.998604e+06,34998.000000,34998.000000,34970.000000,24.990000,1376.370000,299729.000000,39.980000,4.00000,...,100.000000,9.000000,19.00000,19994.000000,100.000000,99859.000000,9.000000,19.000000,14.000000,1.000000

In [5]:
df.dropna()

Empty DataFrame
Columns: [id, member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, url, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, collections_12_mths_ex_med, mths_since_last_major_derog, policy_code, application_type, annual_inc_joint, dti_joint, verification_status_joint, acc_now_delinq, tot_coll_amt, tot_cur_bal, open_acc_6m, open_il_6m, open_il_12m, open_il_24m, mths_since_rcnt_il, total_bal_il, il_util, open_rv_12m, open_rv_24m, max_bal_bc, all_util, total_rev_hi_lim, inq_fi, total_cu_tl, inq_last_12m, Default]
Index: []

[0 rows x 75 columns]

In [6]:
df.loc[df['emp_title'] == 'Analyst']

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,Default
0,1000000,7423388,5583,5583,5530,60 months,9.02,177.59,C,F5,...,38.5,3,8,7195,8.6,75743,2,7,14,0
1,1000001,7550634,12889,12889,12818,60 months,21.10,486.26,E,F5,...,89.6,2,16,15986,76.7,20687,3,12,11,0
47,1000047,1271836,17832,17832,17761,36 months,15.92,626.22,D,D2,...,39.7,6,2,14516,72.1,37505,2,10,3,0
51,1000051,9585377,4081,4081,4044,60 months,22.12,156.11,D,A5,...,65.7,7,10,13937,71.0,24401,4,2,5,0
58,1000058,3879190,20363,20363,20276,36 months,7.02,628.94,A,C5,...,85.1,3,18,10863,82.7,73670,7,9,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967,1001967,9481209,7771,7771,7747,36 months,12.19,258.81,G,B1,...,32.2,2,10,16937,45.1,19905,4,16,3,0
1977,1001977,7473507,4791,4791,4772,36 months,23.64,187.06,F,G5,...,13.4,0,13,11746,17.5,89697,8,14,3,0
1979,1001979,6137997,18888,18888,18818,36 months,24.00,741.03,A,C1,...,3.0,3,15,607,19.4,41852,2,5,14,1
1997,1001997,9415414,25484,25484,25471,36 months,13.41,863.70,G,C3,...,18.1,8,4,11673,42.2,16326,9,10,14,0
1999,1001999,5609688,1191,1191,1143,60 months,24.65,47.13,E,D5,...,0.9,1,19,19739,77.0,87322,2,13,12,1

In [7]:
df.groupby('emp_title')['installment'].sum()

emp_title
Accountant    132655.32
Analyst       132553.62
Consultant    149320.13
Developer     147163.81
Doctor        131618.20
Engineer      140231.58
Manager       145530.68
Teacher       148907.73
Name: installment, dtype: float64

In [8]:
df.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'Default'], dtype=object)

In [9]:
df['emp_length'].unique()

array(['7 years', '10+ years', '2 years', '6 years', '1 year', '8 years',
       '4 years', '5 years', '< 1 year', '9 years', '3 years'],
      dtype=object)

In [10]:
df['emp_length'] = df['emp_length'].str.replace(' years',' ')
df['emp_length'] = df['emp_length'].str.replace('+',' ')
df['emp_length'] = df['emp_length'].str.replace('< 1 year',str(0))

In [11]:
# convert str to integer
df['emp_length'] = pd.to_numeric(df['emp_length'], errors='coerce').fillna(0).astype('Int64')
df['emp_length'].unique()

<IntegerArray>
[7, 10, 2, 6, 0, 8, 4, 5, 9, 3]
Length: 10, dtype: Int64

In [12]:
df['earliest_cr_line_date'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y', errors='coerce')

# Fixing years that are incorrectly parsed (assuming dates before 2025 should be in the 1900s)
df.loc[df['earliest_cr_line_date'].dt.year > 2025, 'earliest_cr_line_date'] -= pd.DateOffset(years=100)
type(df['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
# calculate overall time has been passed after the earliest credit line
df['earliest_cr_line_date_month'] = round((pd.to_datetime('2026-06-26') - df['earliest_cr_line_date']).dt.days/30.44)
df['earliest_cr_line_date_month'].describe()

count    2000.000000
mean      378.736000
std       105.315236
min       199.000000
25%       286.000000
50%       380.000000
75%       472.000000
max       558.000000
Name: earliest_cr_line_date_month, dtype: float64

In [14]:
# Import the function to split data into training and test sets 
from sklearn.model_selection import train_test_split

# Drop rows where the target column 'loan status is missing
# This is important because missing target values can't be used for training and testing
df=df.dropna(subset=['loan_status'])

# Separate the features (input variables) from the target (label to predict)
# x will contain all columns except 'loan_status'
# y will contain only 'loan_status' column
x=df.drop(columns='loan_status')
y=df['loan_status']

# Split the data set into training and testing sets
# test size=0.2 means 20% of the data goes to the test set and 80% to the training set
# random state=30 ensure the split is reproducible every time the code is run
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=30)

# Print the shape (dimentions) of each dataset to confirm the split
print("Trainig features shape:", x_train.shape) # Rows and Columns in x_train
print("Trainig labels shape:", y_train.shape)   # Number of labels in y_train
print("Test features shape:", x_test.shape)     # Rows and Columns in x_test
print("Test labels shape:", y_test.shape)       # Number of labels in y_test

Trainig features shape: (1600, 76)
Trainig labels shape: (1600,)
Test features shape: (400, 76)
Test labels shape: (400,)